
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.labcompi1.demo1.parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int RECTANGLE = 12;
  public static final int INTEGER = 8;
  public static final int DIVIDE = 5;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int GRAPH = 9;
  public static final int COMMA = 14;
  public static final int error = 1;
  public static final int SEMICOLON = 13;
  public static final int RPAREN = 7;
  public static final int CIRCLE = 10;
  public static final int TIMES = 4;
  public static final int SQUARE = 11;
  public static final int LPAREN = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "INTEGER",
  "GRAPH",
  "CIRCLE",
  "SQUARE",
  "RECTANGLE",
  "SEMICOLON",
  "COMMA"
  };
}

