
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.labcompi1.demo1.parser;

import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SimpleParser1 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return SimpleParser1Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public SimpleParser1() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SimpleParser1(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SimpleParser1(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\005\000\002\002\005\000\002\002\004\000\002\002" +
    "\003\000\002\003\005\000\002\003\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\011\000\004\004\004\001\002\000\010\002\ufffd\005" +
    "\ufffd\006\ufffd\001\002\000\010\002\uffff\005\uffff\006\012" +
    "\001\002\000\006\002\010\005\007\001\002\000\004\004" +
    "\004\001\002\000\004\002\000\001\002\000\010\002\001" +
    "\005\001\006\012\001\002\000\004\004\013\001\002\000" +
    "\010\002\ufffe\005\ufffe\006\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\011\000\006\002\005\003\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\003\010" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SimpleParser1$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SimpleParser1$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SimpleParser1$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public SimpleParser1(SimpleLexer1 lexer) {
        super(lexer);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SimpleParser1$actions {
  private final SimpleParser1 parser;

  /** Constructor */
  CUP$SimpleParser1$actions(SimpleParser1 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SimpleParser1$do_action_part00000000(
    int                        CUP$SimpleParser1$act_num,
    java_cup.runtime.lr_parser CUP$SimpleParser1$parser,
    java.util.Stack            CUP$SimpleParser1$stack,
    int                        CUP$SimpleParser1$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SimpleParser1$result;

      /* select the action based on the action number */
      switch (CUP$SimpleParser1$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // sum ::= sum PLUS prod 
            {
              Integer RESULT =null;
		int sumaleft = ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.elementAt(CUP$SimpleParser1$top-2)).left;
		int sumaright = ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.elementAt(CUP$SimpleParser1$top-2)).right;
		Integer suma = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser1$stack.elementAt(CUP$SimpleParser1$top-2)).value;
		int productoleft = ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()).left;
		int productoright = ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()).right;
		Integer producto = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser1$stack.peek()).value;
		 RESULT = suma + producto; 
              CUP$SimpleParser1$result = parser.getSymbolFactory().newSymbol("sum",0, ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.elementAt(CUP$SimpleParser1$top-2)), ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()), RESULT);
            }
          return CUP$SimpleParser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= sum EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.elementAt(CUP$SimpleParser1$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.elementAt(CUP$SimpleParser1$top-1)).right;
		Integer start_val = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser1$stack.elementAt(CUP$SimpleParser1$top-1)).value;
		RESULT = start_val;
              CUP$SimpleParser1$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.elementAt(CUP$SimpleParser1$top-1)), ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SimpleParser1$parser.done_parsing();
          return CUP$SimpleParser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // sum ::= prod 
            {
              Integer RESULT =null;
		int productoleft = ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()).left;
		int productoright = ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()).right;
		Integer producto = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser1$stack.peek()).value;
		 RESULT = producto; 
              CUP$SimpleParser1$result = parser.getSymbolFactory().newSymbol("sum",0, ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()), ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()), RESULT);
            }
          return CUP$SimpleParser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // prod ::= prod TIMES INTEGER 
            {
              Integer RESULT =null;
		int productoleft = ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.elementAt(CUP$SimpleParser1$top-2)).left;
		int productoright = ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.elementAt(CUP$SimpleParser1$top-2)).right;
		Integer producto = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser1$stack.elementAt(CUP$SimpleParser1$top-2)).value;
		int enteroleft = ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()).left;
		int enteroright = ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()).right;
		Token entero = (Token)((java_cup.runtime.Symbol) CUP$SimpleParser1$stack.peek()).value;
		 RESULT = producto * Integer.valueOf(entero.getValue());
              CUP$SimpleParser1$result = parser.getSymbolFactory().newSymbol("prod",1, ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.elementAt(CUP$SimpleParser1$top-2)), ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()), RESULT);
            }
          return CUP$SimpleParser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // prod ::= INTEGER 
            {
              Integer RESULT =null;
		int enteroleft = ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()).left;
		int enteroright = ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()).right;
		Token entero = (Token)((java_cup.runtime.Symbol) CUP$SimpleParser1$stack.peek()).value;
		 RESULT = Integer.valueOf(entero.getValue()); 
              CUP$SimpleParser1$result = parser.getSymbolFactory().newSymbol("prod",1, ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()), ((java_cup.runtime.Symbol)CUP$SimpleParser1$stack.peek()), RESULT);
            }
          return CUP$SimpleParser1$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SimpleParser1$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SimpleParser1$do_action(
    int                        CUP$SimpleParser1$act_num,
    java_cup.runtime.lr_parser CUP$SimpleParser1$parser,
    java.util.Stack            CUP$SimpleParser1$stack,
    int                        CUP$SimpleParser1$top)
    throws java.lang.Exception
    {
              return CUP$SimpleParser1$do_action_part00000000(
                               CUP$SimpleParser1$act_num,
                               CUP$SimpleParser1$parser,
                               CUP$SimpleParser1$stack,
                               CUP$SimpleParser1$top);
    }
}

}
