
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.labcompi1.demo1.parser;

/** CUP generated class containing symbol constants. */
public class SimpleParserSym {
  /* terminals */
  public static final int INTEGER = 7;
  public static final int POW = 6;
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int MINUS = 3;
  public static final int DIVIDE = 5;
  public static final int TIMES = 4;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "POW",
  "INTEGER"
  };
}

