
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.labcompi1.demo1.parser;

import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SimpleParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return SimpleParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public SimpleParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SimpleParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SimpleParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\010\000\002\002\005\000\002\002\004\000\002\002" +
    "\005\000\002\002\003\000\002\003\005\000\002\003\005" +
    "\000\002\003\003\000\002\004\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\016\000\004\011\004\001\002\000\014\002\ufffa\004" +
    "\ufffa\005\ufffa\006\ufffa\007\ufffa\001\002\000\014\002\ufffe" +
    "\004\ufffe\005\ufffe\006\015\007\014\001\002\000\010\002" +
    "\012\004\010\005\011\001\002\000\014\002\ufffb\004\ufffb" +
    "\005\ufffb\006\ufffb\007\ufffb\001\002\000\004\011\004\001" +
    "\002\000\004\011\004\001\002\000\004\002\000\001\002" +
    "\000\014\002\uffff\004\uffff\005\uffff\006\015\007\014\001" +
    "\002\000\004\011\004\001\002\000\004\011\004\001\002" +
    "\000\014\002\ufffd\004\ufffd\005\ufffd\006\ufffd\007\ufffd\001" +
    "\002\000\014\002\ufffc\004\ufffc\005\ufffc\006\ufffc\007\ufffc" +
    "\001\002\000\014\002\001\004\001\005\001\006\015\007" +
    "\014\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\016\000\010\002\005\003\004\004\006\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\003\017\004\006\001\001\000\006\003" +
    "\012\004\006\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\004\016\001\001\000\004\004\015\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SimpleParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SimpleParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SimpleParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public SimpleParser(SimpleLexer lexer) {
        super(lexer);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SimpleParser$actions {
  private final SimpleParser parser;

  /** Constructor */
  CUP$SimpleParser$actions(SimpleParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SimpleParser$do_action_part00000000(
    int                        CUP$SimpleParser$act_num,
    java_cup.runtime.lr_parser CUP$SimpleParser$parser,
    java.util.Stack            CUP$SimpleParser$stack,
    int                        CUP$SimpleParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SimpleParser$result;

      /* select the action based on the action number */
      switch (CUP$SimpleParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // a ::= a PLUS b 
            {
              Integer RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)).right;
		Integer n1 = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()).right;
		Integer n2 = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser$stack.peek()).value;
		 RESULT = n1 + n2; 
              CUP$SimpleParser$result = parser.getSymbolFactory().newSymbol("a",0, ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)), ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()), RESULT);
            }
          return CUP$SimpleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= a EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-1)).right;
		Integer start_val = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-1)).value;
		RESULT = start_val;
              CUP$SimpleParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-1)), ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SimpleParser$parser.done_parsing();
          return CUP$SimpleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // a ::= a MINUS b 
            {
              Integer RESULT =null;
		int variable1left = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)).left;
		int variable1right = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)).right;
		Integer variable1 = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)).value;
		int variable2left = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()).left;
		int variable2right = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()).right;
		Integer variable2 = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser$stack.peek()).value;
		 RESULT = variable1 - variable2; 
              CUP$SimpleParser$result = parser.getSymbolFactory().newSymbol("a",0, ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)), ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()), RESULT);
            }
          return CUP$SimpleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // a ::= b 
            {
              Integer RESULT =null;
		int numeritoleft = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()).left;
		int numeritoright = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()).right;
		Integer numerito = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser$stack.peek()).value;
		 RESULT = numerito; 
              CUP$SimpleParser$result = parser.getSymbolFactory().newSymbol("a",0, ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()), RESULT);
            }
          return CUP$SimpleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // b ::= b TIMES c 
            {
              Integer RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)).right;
		Integer n1 = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()).right;
		Integer n2 = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser$stack.peek()).value;
		 RESULT = n1 * n2; 
              CUP$SimpleParser$result = parser.getSymbolFactory().newSymbol("b",1, ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)), ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()), RESULT);
            }
          return CUP$SimpleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // b ::= b DIVIDE c 
            {
              Integer RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)).right;
		Integer n1 = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()).right;
		Integer n2 = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser$stack.peek()).value;
		
                if (n2 == 0) {
                    throw new IllegalArgumentException("Dividiendo por cero");
                }
                RESULT = n1 / n2;
            
              CUP$SimpleParser$result = parser.getSymbolFactory().newSymbol("b",1, ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.elementAt(CUP$SimpleParser$top-2)), ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()), RESULT);
            }
          return CUP$SimpleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // b ::= c 
            {
              Integer RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()).right;
		Integer n1 = (Integer)((java_cup.runtime.Symbol) CUP$SimpleParser$stack.peek()).value;
		 RESULT = n1; 
              CUP$SimpleParser$result = parser.getSymbolFactory().newSymbol("b",1, ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()), RESULT);
            }
          return CUP$SimpleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // c ::= INTEGER 
            {
              Integer RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()).right;
		Token n1 = (Token)((java_cup.runtime.Symbol) CUP$SimpleParser$stack.peek()).value;
		 RESULT = Integer.valueOf(n1.getValue()); 
              CUP$SimpleParser$result = parser.getSymbolFactory().newSymbol("c",2, ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SimpleParser$stack.peek()), RESULT);
            }
          return CUP$SimpleParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SimpleParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SimpleParser$do_action(
    int                        CUP$SimpleParser$act_num,
    java_cup.runtime.lr_parser CUP$SimpleParser$parser,
    java.util.Stack            CUP$SimpleParser$stack,
    int                        CUP$SimpleParser$top)
    throws java.lang.Exception
    {
              return CUP$SimpleParser$do_action_part00000000(
                               CUP$SimpleParser$act_num,
                               CUP$SimpleParser$parser,
                               CUP$SimpleParser$stack,
                               CUP$SimpleParser$top);
    }
}

}
